SET client_encoding = 'UTF8';
INSERT INTO Departamentos(nombre) VALUES ('Amazonas');
INSERT INTO Departamentos(nombre) VALUES ('Áncash');
INSERT INTO Departamentos(nombre) VALUES ('Apurímac');
INSERT INTO Departamentos(nombre) VALUES ('Arequipa');
INSERT INTO Departamentos(nombre) VALUES ('Ayacucho');
INSERT INTO Departamentos(nombre) VALUES ('Cajamarca');
INSERT INTO Departamentos(nombre) VALUES ('Callao');
INSERT INTO Departamentos(nombre) VALUES ('Cusco');
INSERT INTO Departamentos(nombre) VALUES ('Huancavelica');
INSERT INTO Departamentos(nombre) VALUES ('Huánuco');
INSERT INTO Departamentos(nombre) VALUES ('Ica');
INSERT INTO Departamentos(nombre) VALUES ('Junín');
INSERT INTO Departamentos(nombre) VALUES ('La Libertad');
INSERT INTO Departamentos(nombre) VALUES ('Lambayeque');
INSERT INTO Departamentos(nombre) VALUES ('Lima');
INSERT INTO Departamentos(nombre) VALUES ('Loreto');
INSERT INTO Departamentos(nombre) VALUES ('Madre de Dios');
INSERT INTO Departamentos(nombre) VALUES ('Moquegua');
INSERT INTO Departamentos(nombre) VALUES ('Pasco');
INSERT INTO Departamentos(nombre) VALUES ('Piura');
INSERT INTO Departamentos(nombre) VALUES ('Puno');
INSERT INTO Departamentos(nombre) VALUES ('San Martín');
INSERT INTO Departamentos(nombre) VALUES ('Tacna');
INSERT INTO Departamentos(nombre) VALUES ('Tumbes');
INSERT INTO Departamentos(nombre) VALUES ('Ucayali');