TRUNCATE TABLE Archivos CASCADE;
TRUNCATE TABLE Agrupamiento CASCADE;
TRUNCATE TABLE Algoritmos CASCADE;
TRUNCATE TABLE Variantes CASCADE;
TRUNCATE TABLE Secuencias CASCADE;
TRUNCATE TABLE Departamentos CASCADE;