TRUNCATE TABLE archivos CASCADE;
TRUNCATE TABLE agrupamiento CASCADE;
TRUNCATE TABLE algoritmos CASCADE;
TRUNCATE TABLE variantes CASCADE;
TRUNCATE TABLE secuencias CASCADE;
TRUNCATE TABLE departamentos CASCADE;